service: example

frameworkVersion: '2'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  country: ${opt:country}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    baseUrl: http://localhost:800
  apiKeys:
    - free:
        - ${opt:stage}-carrg
  usagePlan:
    - free:
        quota:
          limit: 10
          offset: 0
          period: MONTH
        throttle:
          burstLimit: 5
          rateLimit: 5
functions:
  add-users:
    handler: src/add_user/handler.main
    events:
     - http:
         path: users
         method: post
         private: true

  get-users:
    handler: src/get_user/handler.main
    events:
     - http:
         path: users
         method: get
         private: true