service: developrz-users-backend

frameworkVersion: '2'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  country: ${opt:country}
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-west-2
  deploymentBucket:
    name: ${self:custom.stage}-${self:custom.country}-car-deployments
    blockPublicAccess: true
  environment:
    BASE_URL: ${env:BASE_URL}
  # apiKeys:
  #   - free:
  #       - ${opt:stage}-carrg
  # usagePlan:
  #   - free:
  #       quota:
  #         limit: 10
  #         offset: 0
  #         period: MONTH
  #       throttle:
  #         burstLimit: 5
  #         rateLimit: 5
  apiGateway:
    shouldStartNameWithService: true

functions:
  add-users:
    handler: src/add_user/handler.main
    description: Crear usarios
    environment:
      POST: ${env:POST}
    events:
     - http:
         path: users
         method: post
        #  private: true

  get-users:
    handler: src/get_user/handler.main
    events:
     - http:
         path: users
         method: get
        #  private: true
